# Generated by Django 3.2.6 on 2021-08-17 04:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Natural', 'Natural'), ('IVF', 'IVF')], max_length=8)),
                ('result', models.CharField(choices=[('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], max_length=15)),
                ('calf_due', models.DateField(blank=True, null=True)),
                ('breed', models.ForeignKey(default='Deleted Breed', on_delete=django.db.models.deletion.SET_DEFAULT, to='Cow.breed')),
                ('cow', models.ForeignKey(default='Deleted cow', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cow', to='Cow.cow')),
                ('stud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bull', to='Cow.cow')),
            ],
        ),
    ]
