# Generated by Django 3.2.6 on 2021-08-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cow', '0002_breeding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
