# Generated by Django 3.2.6 on 2021-08-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cow', '0005_cow_vaccinated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='status',
            field=models.CharField(choices=[('', 'Select a status'), ('Calf', 'Calf'), ('Hiefer', 'Hiefer'), ('Cow', 'Cow'), ('Bull', 'Bull')], max_length=30),
        ),
    ]
