# Generated by Django 3.2.6 on 2021-08-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cow', '0006_alter_cow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeding',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cow.breed'),
        ),
    ]
