# Generated by Django 3.2.6 on 2021-08-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cow', '0009_alter_breeding_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
