# Generated by Django 3.2.6 on 2021-08-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cow', '0011_pregnantcow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breeding',
            name='calf_due',
        ),
    ]
