# Generated by Django 3.2.6 on 2021-08-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cow', '0012_remove_breeding_calf_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnantcow',
            name='calf_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
