# Generated by Django 3.2.6 on 2021-08-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cow', '0013_pregnantcow_calf_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Age',
                'verbose_name_plural': 'Ages',
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Cow', 'Cow'), ('Employee', 'Employee'), ('Monthly Report', 'Monthly Report'), ('Invoice', 'Invoice'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='item',
            field=models.CharField(choices=[('Paddy Straw', 'Paddy Straw'), ('Feed', 'Feed'), ('Areca Leaf Powder', 'Areca Leaf Powder'), ('Medicine', 'Medicine'), ('Salary', 'Salary'), ('Current Bill', 'Current Bill'), ('NewsPaper Bill', 'NewsPaper Bill'), ('Repair & Maintainance', 'Repair & Maintainance'), ('Food', 'Food'), ('Transport', 'Transport'), ('Other', 'Other')], max_length=30),
        ),
    ]
