# Generated by Django 3.2.6 on 2021-08-22 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cow', '0014_auto_20210822_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='cow_age',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='age', to='Cow.age'),
        ),
    ]
