# Generated by Django 3.2.6 on 2021-08-22 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cow', '0015_cow_cow_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='cow_age_when_brought',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='age_when_brought', to='Cow.age'),
        ),
    ]
