# Generated by Django 3.2.6 on 2021-08-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cow', '0016_cow_cow_age_when_brought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cow',
            name='age',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='age_duration_type',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='age_when_brought',
        ),
    ]
