# Generated by Django 3.2.6 on 2021-08-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cow', '0018_auto_20210828_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='seen',
            field=models.BooleanField(null=True),
        ),
    ]
