# Generated by Django 3.2.6 on 2021-08-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cow', '0019_auto_20210828_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
