# Generated by Django 3.2.6 on 2021-08-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cow', '0020_alter_inbox_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
