# Generated by Django 3.2.6 on 2021-08-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cow', '0021_alter_inbox_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
