# Generated by Django 3.2.6 on 2021-08-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cow', '0022_alter_inbox_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeding',
            name='category',
            field=models.CharField(choices=[('Natural', 'Natural'), ('Artificial Insemination', 'AI')], max_length=25),
        ),
    ]
